<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="PCB_Project1.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Value" Caption="Value" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Value="1uF" Comment="Cap Semi" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C1, C3, C4, C5" Footprint="0402" LibRef="Cap Semi" Quantity="4"></ROW>
    <ROW Value="100uF" Comment="Cap Semi" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C2" Footprint="C2512" LibRef="Cap Semi" Quantity="1"></ROW>
    <ROW Value="" Comment="XC6206P332MR" Description="" Designator="IC1" Footprint="SOT-23" LibRef="XC6206P332MR" Quantity="1"></ROW>
    <ROW Value="" Comment="SH-4.0" Description="" Designator="P1" Footprint="SH-4.0" LibRef="SH-4.0" Quantity="1"></ROW>
    <ROW Value="10K" Comment="Res2" Description="Resistor" Designator="R1, R2, R3, R4, R5" Footprint="0402" LibRef="Res2" Quantity="5"></ROW>
    <ROW Value="330" Comment="Res2" Description="Resistor" Designator="R6" Footprint="0402" LibRef="Res2" Quantity="1"></ROW>
    <ROW Value="" Comment="SI2302" Description="" Designator="U1, U3" Footprint="SOT-23" LibRef="IRLML2244TRPbF" Quantity="2"></ROW>
    <ROW Value="" Comment="APDS-9960" Description="" Designator="U2" Footprint="APDS-9960" LibRef="APDS-9960" Quantity="1"></ROW>
    <ROW Value="" Comment="Via" Description="" Designator="V1, V2" Footprint="Via" LibRef="Via" Quantity="2"></ROW>
  </ROWS>
</GRID>
